version: '1'

services:

  backend:
    build:
      context: ./../real-chat-backend
      dockerfile: ./../real-chat-backend/backend.dockerfile
    restart: always
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
    
  
  frontend:
    build:
      context: ./../real-chat-frontend
      dockerfile: ./../real-chat-frontend/front-end.dockerfile
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      NEXT_PUBLIC_ENV_AREA: production